services:
  echo_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "65432:65432"

  echo_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - echo_server
